// src/components/ShareButton.tsx
"use client";

import { useState, useCallback } from "react";

interface ReviewIssue {
  type: string;
  severity: string;
  title: string;
  line?: number;
}

interface ReviewData {
  summary: string;
  issues: ReviewIssue[];
  overallScore: number;
  languageDetected: string;
}

interface Props {
  data: ReviewData;
}

export default function ShareButton({ data }: Props) {
  const [copied, setCopied] = useState(false);

  const handleShare = useCallback(async () => {
    const lines: string[] = [
      `CodeLens Review - Score: ${data.overallScore}/100`,
      `Language: ${data.languageDetected}`,
      "",
      data.summary,
      "",
    ];

    if (data.issues.length > 0) {
      lines.push(`Issues Found (${data.issues.length}):`);
      data.issues.forEach((issue, i) => {
        const lineRef = issue.line != null ? ` (line ${issue.line})` : "";
        lines.push(`  ${i + 1}. [${issue.severity.toUpperCase()}] ${issue.title}${lineRef}`);
      });
    } else {
      lines.push("No issues found!");
    }

    lines.push("", "-- Generated by CodeLens");

    const text = lines.join("\n");

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // silent fail
    }
  }, [data]);

  return (
    <button
      onClick={handleShare}
      className="flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs font-medium transition-colors"
      style={{
        backgroundColor: copied ? "var(--accent)" : "var(--bg-secondary)",
        color: copied ? "#fff" : "var(--text-secondary)",
      }}
      aria-label="Share review summary"
    >
      {copied ? (
        <>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="20 6 9 17 4 12" />
          </svg>
          <span className="hidden sm:inline">Copied!</span>
        </>
      ) : (
        <>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <circle cx="18" cy="5" r="3" />
            <circle cx="6" cy="12" r="3" />
            <circle cx="18" cy="19" r="3" />
            <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
            <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
          </svg>
          <span className="hidden sm:inline">Share</span>
        </>
      )}
    </button>
  );
}